-- Generated from art/aseprite/hats/hats_manifest.json. Do not edit by hand.
return {
  source = "aseprite_master",
  source_path = "art/aseprite/hats/teti_track_hat_master.aseprite",
  source_sha256 = "a92a7fea46f665f4bfff3a82758e083df24ad80599e427294561d4f6e0bd3a5f",
  manifest_sha256 = "b837ffb01d3cf04ec52cde483dbf8c7963d3c2127bca971c97c3d25620e23c8e",
  atlas_sha256 = "4ae36bc0bbf9943b7d3f228fbd1e16c2687a00fa27c50d1cae03ed9f46feb5a2",
  build_id = "204bb6d376c5972f",
  cache = "fresh",
  render_layer = "world",
  transform = "linked_to_body",
  expected_count = 18,
  anchor = { name = "head_top_center", x = 64, y = 16 },
  order = { "none", "beanie", "engineer", "antenna", "warning_light", "sprout", "focus_goggles", "happy_cap", "sad_hood", "loading_ring", "cpu_core", "network_node", "mouse_cursor", "click_spark", "drag_handle", "token_core", "gateway_node", "fleet_signal" },
  menu = { "none", "beanie", "engineer", "antenna", "warning_light", "sprout", "focus_goggles", "happy_cap", "sad_hood", "loading_ring", "cpu_core", "network_node", "mouse_cursor", "click_spark", "drag_handle", "token_core", "gateway_node", "fleet_signal" },
  by_id = {
    ["none"] = { id = "none", label = "None", category = "basic", sprite = 36, asset_key = "hat_none_128", file = "pet-runtime/assets/master_128/hats/hat_none_128.png", source_tag = "none", source_frame = 0 },
    ["beanie"] = { id = "beanie", label = "Beanie", category = "basic", sprite = 37, asset_key = "hat_beanie_128", file = "pet-runtime/assets/master_128/hats/hat_beanie_128.png", source_tag = "beanie", source_frame = 1, bounds = { x = 40, y = 8, w = 49, h = 18 } },
    ["engineer"] = { id = "engineer", label = "Engineer", category = "basic", sprite = 38, asset_key = "hat_engineer_128", file = "pet-runtime/assets/master_128/hats/hat_engineer_128.png", source_tag = "engineer", source_frame = 2, bounds = { x = 39, y = 10, w = 51, h = 16 } },
    ["antenna"] = { id = "antenna", label = "Antenna", category = "basic", sprite = 39, asset_key = "hat_antenna_128", file = "pet-runtime/assets/master_128/hats/hat_antenna_128.png", source_tag = "antenna", source_frame = 3, bounds = { x = 52, y = 8, w = 25, h = 18 } },
    ["warning_light"] = { id = "warning_light", label = "Warning Light", category = "basic", sprite = 40, asset_key = "hat_warning_light_128", file = "pet-runtime/assets/master_128/hats/hat_warning_light_128.png", source_tag = "warning_light", source_frame = 4, bounds = { x = 50, y = 11, w = 29, h = 15 } },
    ["sprout"] = { id = "sprout", label = "Sprout", category = "basic", sprite = 41, asset_key = "hat_sprout_128", file = "pet-runtime/assets/master_128/hats/hat_sprout_128.png", source_tag = "sprout", source_frame = 5, bounds = { x = 48, y = 8, w = 33, h = 17 } },
    ["focus_goggles"] = { id = "focus_goggles", label = "Focus Goggles", category = "emotion", sprite = 42, asset_key = "hat_focus_goggles_128", file = "pet-runtime/assets/master_128/hats/hat_focus_goggles_128.png", source_tag = "focus_goggles", source_frame = 6, bounds = { x = 39, y = 13, w = 51, h = 12 } },
    ["happy_cap"] = { id = "happy_cap", label = "Happy Cap", category = "emotion", sprite = 43, asset_key = "hat_happy_cap_128", file = "pet-runtime/assets/master_128/hats/hat_happy_cap_128.png", source_tag = "happy_cap", source_frame = 7, bounds = { x = 39, y = 11, w = 48, h = 15 } },
    ["sad_hood"] = { id = "sad_hood", label = "Sad Hood", category = "emotion", sprite = 44, asset_key = "hat_sad_hood_128", file = "pet-runtime/assets/master_128/hats/hat_sad_hood_128.png", source_tag = "sad_hood", source_frame = 8, bounds = { x = 43, y = 9, w = 43, h = 17 } },
    ["loading_ring"] = { id = "loading_ring", label = "Loading Ring", category = "system", sprite = 45, asset_key = "hat_loading_ring_128", file = "pet-runtime/assets/master_128/hats/hat_loading_ring_128.png", source_tag = "loading_ring", source_frame = 9, bounds = { x = 55, y = 8, w = 19, h = 17 } },
    ["cpu_core"] = { id = "cpu_core", label = "CPU Core", category = "system", sprite = 46, asset_key = "hat_cpu_core_128", file = "pet-runtime/assets/master_128/hats/hat_cpu_core_128.png", source_tag = "cpu_core", source_frame = 10, bounds = { x = 49, y = 10, w = 31, h = 14 } },
    ["network_node"] = { id = "network_node", label = "Network Node", category = "system", sprite = 47, asset_key = "hat_network_node_128", file = "pet-runtime/assets/master_128/hats/hat_network_node_128.png", source_tag = "network_node", source_frame = 11, bounds = { x = 44, y = 8, w = 41, h = 17 } },
    ["mouse_cursor"] = { id = "mouse_cursor", label = "Mouse Cursor", category = "interaction", sprite = 48, asset_key = "hat_mouse_cursor_128", file = "pet-runtime/assets/master_128/hats/hat_mouse_cursor_128.png", source_tag = "mouse_cursor", source_frame = 12, bounds = { x = 49, y = 9, w = 31, h = 17 } },
    ["click_spark"] = { id = "click_spark", label = "Click Spark", category = "interaction", sprite = 49, asset_key = "hat_click_spark_128", file = "pet-runtime/assets/master_128/hats/hat_click_spark_128.png", source_tag = "click_spark", source_frame = 13, bounds = { x = 53, y = 8, w = 23, h = 18 } },
    ["drag_handle"] = { id = "drag_handle", label = "Drag Handle", category = "interaction", sprite = 50, asset_key = "hat_drag_handle_128", file = "pet-runtime/assets/master_128/hats/hat_drag_handle_128.png", source_tag = "drag_handle", source_frame = 14, bounds = { x = 43, y = 12, w = 43, h = 12 } },
    ["token_core"] = { id = "token_core", label = "Token Core", category = "tokenfleet", sprite = 51, asset_key = "hat_token_core_128", file = "pet-runtime/assets/master_128/hats/hat_token_core_128.png", source_tag = "token_core", source_frame = 15, bounds = { x = 54, y = 8, w = 21, h = 18 } },
    ["gateway_node"] = { id = "gateway_node", label = "Gateway Node", category = "tokenfleet", sprite = 52, asset_key = "hat_gateway_node_128", file = "pet-runtime/assets/master_128/hats/hat_gateway_node_128.png", source_tag = "gateway_node", source_frame = 16, bounds = { x = 49, y = 9, w = 31, h = 17 } },
    ["fleet_signal"] = { id = "fleet_signal", label = "Fleet Signal", category = "tokenfleet", sprite = 53, asset_key = "hat_fleet_signal_128", file = "pet-runtime/assets/master_128/hats/hat_fleet_signal_128.png", source_tag = "fleet_signal", source_frame = 17, bounds = { x = 53, y = 9, w = 23, h = 17 } },
  },
}
