-- Generated by tools/asset-build/build_master_128.py. Do not edit by hand.
return {
  front = 1,
  side = 2,
  face_neutral = 3,
  face_blink = 4,
  idle_1 = 9,
  idle_2 = 10,
  move_left = 11,
  move_right = 12,
  body_bounds = { x = 16, y = 18, w = 97, h = 104 },
  idle_breathe = { 13, 14, 15, 16 },
  move_left_track = { 17, 18, 19, 20, 21, 22 },
  move_right_track = { 23, 24, 25, 26, 27, 28 },
  face_clear = 29,
  face_overlay = {
    neutral = 30,
    blink = 31,
    sleepy = 32,
    focused = 33,
    warning = 34,
    collapsed = 35,
  },
}
